# Generated by Django 6.0.2 on 2026-03-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date',
            new_name='date_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
