# Generated by Django 6.0.2 on 2026-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgestore', '0002_rename_date_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
