# Generated by Django 6.0.2 on 2026-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgestore', '0003_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='urlimg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
