# Generated by Django 6.0.2 on 2026-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgestore', '0004_book_urlimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
